### ISSUE TITLE
java.lang.AbstractMethodError: abstract method not implemented

### ISSUE THREAD

**Issue by Niroj08** [PhilJay/MPAndroidChart-Realm#5]
java.lang.AbstractMethodError: abstract method not implemented
                                                                            at com.github.mikephil.charting.data.BaseDataSet.getEntryForXValue(BaseDataSet.java)
                                                                            at com.github.mikephil.charting.renderer.BarLineScatterCandleBubbleRenderer$XBounds.set(BarLineScatterCandleBubbleRenderer.java:88)
                                                                            at com.github.mikephil.charting.renderer.LineChartRenderer.drawCubicBezier(LineChartRenderer.java:189)
                                                                            at com.github.mikephil.charting.renderer.LineChartRenderer.drawDataSet(LineChartRenderer.java:118)
                                                                            at com.github.mikephil.charting.renderer.LineChartRenderer.drawData(LineChartRenderer.java:96)
                                                                            at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:227)
                                                                            at android.view.View.draw(View.java:14629)
                                                                            at android.view.View.getDisplayList(View.java:13523)
                                                                            at android.view.View.getDisplayList(View.java:13565)
                                                                            at android.view.View.draw(View.java:14343)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3228)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3065)
                                                                            at android.view.View.getDisplayList(View.java:13518)
                                                                            at android.view.View.getDisplayList(View.java:13565)
                                                                            at android.view.View.draw(View.java:14343)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3228)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3065)
                                                                            at android.view.View.draw(View.java:14632)
                                                                            at android.widget.FrameLayout.draw(FrameLayout.java:472)
                                                                            at android.view.View.getDisplayList(View.java:13523)
                                                                            at android.view.View.getDisplayList(View.java:13565)
                                                                            at android.view.View.draw(View.java:14343)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3228)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3065)
                                                                            at android.view.View.getDisplayList(View.java:13518)
                                                                            at android.view.View.getDisplayList(View.java:13565)
                                                                            at android.view.View.draw(View.java:14343)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3228)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3065)
                                                                            at android.view.View.draw(View.java:14632)
                                                                            at android.widget.FrameLayout.draw(FrameLayout.java:472)
                                                                            at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2456)
                                                                            at android.view.View.getDisplayList(View.java:13523)
                                                                            at android.view.View.getDisplayList(View.java:13565)
                                                                            at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1577)
                                                                            at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1451)
                                                                            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2398)
                                                                            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2264)
                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1892)
                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1006)
                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5652)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                            at android.os.Handler.handleCallback(Handler.java:733)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:136)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5433)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
                                                                            at dalvik.system.NativeStart.main(Native Method)

**Comment by Niroj08** [comment]
BarData works very fine, when i come to work with LineData it gives this error..
amazing :/
